### DISCUSSION TITLE
Cancel request and depended spawned tasks for streamed data

### DISCUSSION THREAD

**Discussion by liketoeatcheese** [robjtede/actix-web-lab#85] [Q&A] [answered]
Hi,

First of all, thank you for your great work!

I'm trying to do data streaming from certain sources, and I can't really figure out how I could cancel whatever was spawned inside that streams the data inside of an Actix request. In the example below, when I make a request to:
`curl http://localhost:8080/hey`

I would receive a continuous stream of:
```log
event: hey_event
data: helloworld
```

The "loop" will be printed on the server's console every second. Even when I cancel the stream on the curl terminal, the "loop" will still be printed to the console.
![image](https://github.com/user-attachments/assets/1038b1ad-235f-4fc6-b9db-0de1e876c8c2)

# Steps to reproduce
```toml
[package]
name = "actix_tokio_cancel"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.6.0", features = ["rustls-0_22"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
actix-web-lab = "0.20.2"
```

```rust
use std::time::Duration;

use actix_web::{web, App, HttpServer, Responder};
use actix_web_lab::sse::{self, Event};
use tokio::io;
use tokio_stream::wrappers::ReceiverStream;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().route("/hey", web::get().to(manual_hello)))
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}

pub async fn manual_hello() -> impl Responder {
    let (stream_tx, stream_rx) = tokio::sync::mpsc::channel::<Result<Event, io::Error>>(100);
    let stream = ReceiverStream::new(stream_rx);
    tokio::spawn(async move {
        loop {
            println!("looping");
            let event = sse::Data::new("hellowolrd").event(format!("hey_event"));
            if stream_tx
                .send(Ok::<_, io::Error>(sse::Event::Data(event)))
                .await
                .is_err()
            {
                break;
            }

            tokio::time::sleep(Duration::from_secs(1)).await;
        }
    });

    sse::Sse::from_stream(stream)
}
```

# Expected behaviour
The infinite loop will stop
